// Code generated by codegen. DO NOT EDIT.

// +k8s:deepcopy-gen=package
// +groupName=upgrade.cattle.io
package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// PlanList is a list of Plan resources
type PlanList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`

	Items []Plan `json:"items"`
}

func NewPlan(namespace, name string, obj Plan) *Plan {
	obj.APIVersion, obj.Kind = SchemeGroupVersion.WithKind("Plan").ToAPIVersionAndKind()
	obj.Name = name
	obj.Namespace = namespace
	return &obj
}
